// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NipedWebApi.Data;

#nullable disable

namespace NipedWebApi.Migrations
{
    [DbContext(typeof(NipedDbContext))]
    [Migration("20250809113126_MIGRATION-NAME")]
    partial class MIGRATIONNAME
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.CholesterolGuideline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuidelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineId")
                        .IsUnique();

                    b.ToTable("CholesterolGuidelines");
                });

            modelBuilder.Entity("WebApplication1.Models.Guideline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Guidelines");
                });

            modelBuilder.Entity("WebApplication1.Models.ValueGuideline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CholesterolGuidelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedsAttention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Optimal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeriousIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CholesterolGuidelineId");

                    b.ToTable("ValueGuidelines");
                });

            modelBuilder.Entity("WebApplication1.Models.CholesterolGuideline", b =>
                {
                    b.HasOne("WebApplication1.Models.Guideline", "Guideline")
                        .WithOne("Cholesterol")
                        .HasForeignKey("WebApplication1.Models.CholesterolGuideline", "GuidelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guideline");
                });

            modelBuilder.Entity("WebApplication1.Models.ValueGuideline", b =>
                {
                    b.HasOne("WebApplication1.Models.CholesterolGuideline", "CholesterolGuideline")
                        .WithMany("ValueGuidelines")
                        .HasForeignKey("CholesterolGuidelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CholesterolGuideline");
                });

            modelBuilder.Entity("WebApplication1.Models.CholesterolGuideline", b =>
                {
                    b.Navigation("ValueGuidelines");
                });

            modelBuilder.Entity("WebApplication1.Models.Guideline", b =>
                {
                    b.Navigation("Cholesterol");
                });
#pragma warning restore 612, 618
        }
    }
}
